# Generated by Django 3.2 on 2023-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
