# Generated by Django 4.2.6 on 2023-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.TextField(),
        ),
    ]
