# Generated by Django 3.2 on 2023-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
